<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bebop.JsonPath\Bebop.JsonPath.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="jsonpath-compliance-test-suite\tests\**\*.json" CopyToOutputDirectory="PreserveNewest" LinkBase="cts\tests" />
    <Content Include="jsonpath-compliance-test-suite\cts.json" CopyToOutputDirectory="PreserveNewest" Link="cts\cts.json" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
